name: Sample
on: [pull_request]

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: echo "::debug::Set the Octocat variable"
    - name: warning
      run: echo "::warning file=sample/Sample.swift,line=10,col=12::[Spacing] remove 1 space"
    - name: error
      run: echo "::error file=sample/Sample.swift,line=11::STring is not defined"
    - name: set-env
      run: echo '::set-env name=SELECTED_COLOR::green'
    - name: debug with env
      run: echo "::debug::The selected color is" $SELECTED_COLOR
